# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
admin = User.create!(email: 'admin@admin', password: '123456', password_confirmation: '123456', is_admin: true)
user = User.create!(email: 'user@user', password: '123456', password_confirmation: '123456', is_admin: false)

post1 = Post.create!(title: 'You call this cat food chase laser',
                     content: "Eat fish on floor hiss at vacuum cleaner, human is washing you why halp oh the horror flee scratch hiss bite grass smells good yet morning beauty routine of licking self. Cereal boxes make for five star accommodation found somthing move i bite it tail tweeting a baseball toilet paper attack claws fluff everywhere meow miao french ciao litterbox for run as fast as i can into another room for no reason sleep over your phone and make cute snoring noises or hunt anything that moves. Kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment curl up and sleep on the freshly laundered towels spill litter box, scratch at owner, destroy all furniture, especially couch for touch water with paw then recoil in horror i vomit in the bed in the middle of the night yet demand to be let outside at once, and expect owner to wait for me as i think about it. Sweet beast give me some of your food give me some of your food give me some of your food meh, i don't want it destroy house in 5 seconds, and spend six hours per day washing, but still have a crusty butthole yet love. Lick sellotape purr like a car engine oh yes, there is my human slave woman she does best pats ever that all i like about her hiss meow but i vomit in the bed in the middle of the night, annoy kitten brother with poking. Stare at the wall, play with food and get confused by dust. Sugar, my siamese, stalks me (in a good way), day and night hunt by meowing loudly at 5am next to human slave food dispenser or morning beauty routine of licking self stand in doorway, unwilling to chose whether to stay in or go out so crash against wall but walk away like nothing happened adventure always. No, you can't close the door, i haven't decided whether or not i wanna go out gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye i love cuddles under the bed, yet put butt in owner's face. Nyaa nyaa sleep nap walk on keyboard flop over, for have secret plans meow all night having their mate disturbing sleeping humans for get scared by doggo also cucumerro . Hey! you there, with the hands scream for no reason at 4 am purr, cat snacks, steal the warm chair right after you get up fart in owners food and see owner, run in terror.", user: admin)

post2 = Post.create!(title: 'Soft kitty warm kitty little ball of furr',
                     content: "Wack the mini furry mouse i want to go outside let me go outside nevermind inside is better and go into a room to decide you didn't want to be in there anyway yet purrr purr littel cat, little cat purr purr swat turds around the house bite plants meow. I is not fat, i is fluffy nya nya nyan, the fat cat sat on the mat bat away with paws make meme, make cute face intently sniff hand. Put toy mouse in food bowl run out of litter box at full speed and sometimes switches in french and say just because well why not or gnaw the corn cob shred all toilet paper and spread around the house. Burrow under covers chirp at birds run off table persian cat jump eat fish so adventure always so run up and down stairs. The dog smells bad hack really likes hummus. Scratch the furniture the dog smells bad.", user: admin)

comment1 = Comment.create!(
  content: 'Cougar american shorthair tomcat, but tomcat. Sphynx. Lion. Jaguar tomcat, cheetah siberian or persian. Panther singapura siberian, russian blue balinese siamese. Egyptian mau grimalkin bengal. Lynx abyssinian.', user: user, post: post1
)
